#!/usr/bin/env bash

echo "$1" > /dev/stderr
#page_number_start=$(
	pdftk "$1" dump_data_utf8 |
grep '^Bookmark\(Page\|Title\)' |
sed 's/[^:]*:\s*//' | paste - - |
grep -vi 'Depósito Recursal' |
grep -vi 'Custas' |
grep -v "\\s\+0$" |
awk -F \\t 'last_ ~ /'"$2"'/ {print $2 ; last_=""} /'"$2"'/ { print $2; last_=$0 }  END { if (last_ ~ /revista/) {print 100} }' |
paste -d"-" - - | bc
#|awk '{sum+=-$0} END {print sum/NR}'
