#!/usr/bin/env bash

grep -o $PROCESSO <([[ -t 0 ]] && ([[ "$1" ]] && cat "$@" || pbpaste) || cat) | sort -n | uniq | tr "\n" ";" | pbcopy
echo "$(pbpaste|grep -o ';' | wc -l) processos" > /dev/stderr
