#!/usr/bin/env bash

extension=${1:${#1}-3}

echo "$1" | grep -o $PROCESSO | tr '\n' '\t'

case $extension in
	pdf)
		pdftotext "$1" - ;;
	rtf)
		dertf "$1" ;;
	*)
		cat "$1" ;;
esac |
	grep -aozP '(JOD|GMJD)\s*/\s*\K([a-z]{1,3})' |
	sed 's/[\/]/\t/g' | tr -d '\n'
echo
