#!/bin/bash

extension=${1:${#1}-3}
processo=$(echo "$1" | grep -o $PROCESSO)

case $extension in
	pdf)
		pdftotext "$1" - ;;
	rtf)
		dertf "$1" ;;
	*)
		cat "$1" ;;
esac |
 	grep -aozP "(GMJD|JOD)\s*/\s*[a-z]{1,3}\s*\K(/\s*[a-z]{1,3})*" |
  	sed 's/[\/]/\t/g' |
	awk -v _p=$processo '
		{ for (i=1;i<=NF;i++) print _p"\t"$i }
		END { if(NR == 0) print _p"\t" }
	'
